### ISSUE TITLE
Link to google doc?

### ISSUE THREAD

**Issue by BrenC222** [pbruvoll/rbnTekkenFrameData#23]
Could we add a link to the google doc in the README file?

**Comment by pbruvoll** [comment]
Thank you for your suggestion. Have updated the readme with link to google docs and added info about the new site https://tekkendocs.com which will be the main focus forward (in addition to rbnorway.org)

**Comment by bren-io** [comment]
Great thanks! Looking forward to T8 and helping with this project

**Comment by pbruvoll** [comment]
Cool, help is appreciated :)
