### ISSUE TITLE
Json wrapper

### ISSUE THREAD

**Issue by bren-io** [pbruvoll/rbnTekkenFrameData#24]
Working on converting the CSV to JSON, I'd like some input on whether or not I should...

a) Have the JSON class handle file I/O, an advantage is that it only loads the file on class instantiation. Also more flexibility since we can create classes per file. More performance?

b) Pass a python object (list, dict, etc) to the JSON class constructor. Advantages are that it keeps the class scope small. File I/O would be handled outside of the class, by another class or script. Cleaner code?

Maybe I don't even need to have this feature although working with JSON has it's own advantages

**Comment by bren-io** [comment]
I went ahead and handled the json and csv files inside of a single class. This way you can create a data structure of empty objects with the functionality to load the data as needed. It's starting to just turn into a class for characters

**Comment by pbruvoll** [comment]
I think both approaches would work well, and I would assume the performance would be about the same either way? Your solution sounds nice, good to encapsulate complexity inside a class :)
What is the use case you are working on? Are you writing something which displays the data?
I've set up a discord for tekkendocs, feel free to join if you like to help out with data or have ideas for the site.
Here is an invite link : https://discord.gg/zjcYyUtg

**Comment by bren-io** [comment]
Thanks for the invite!

Currently yes I would like to just display the data, ideally make a full app or at least an API in which we can all use to retrieve the data. 

Is there a separate repo for the current website?

I would love to have a Namco Bandai release an official API doc for developers something like Riot does with League of Legends. To end up with an app like [https://u.gg/](url) or [https://www.op.gg/](url)

**Comment by bren-io** [comment]
Heres what I have done so far. There are some encoding issues I noticed that I will need to resolve, it's usually special characters like ``` ' ``` and such. Also need to verify that when NaN (not a number?) appears that it is intended

https://github.com/BrenC222/rbnTekkenFrameData/tree/interactive

You can see the output in data/

**Comment by pbruvoll** [comment]
> Thanks for the invite!
> 
> Currently yes I would like to just display the data, ideally make a full app or at least an API in which we can all use to retrieve the data.
> 
> Is there a separate repo for the current website?
> 
> I would love to have a Namco Bandai release an official API doc for developers something like Riot does with League of Legends. To end up with an app like [https://u.gg/](url) or [https://www.op.gg/](url)

I wasn't aware of those sites. Very cool. Would be nice if namco released such apis.
There is a separate repo for the app. Currently it is not public, but I'm considering to change it.
